---
title: 重学 Go 语言：基础篇-36
---
<article id="topicContainer" class="column_content"><h2 class="topic_title"></h2><div><p><div class="toc">
<ul>
<li><ul>
<li><a href="#320panicrecover">3-20 panic和recover</a><ul>
<li><a href="#20defer">20 确保defer得以执行</a></li>
<li><a href="#20panic">20 仅最后一个panic会被捕获</a></li>
<li><a href="#20recover">20 必须在延迟函数中直接调用recover</a></li>
<li><a href="#20">20 使用匿名函数保护代码片段</a></li>
<li><a href="#20errorvspanic">20 error vs panic</a></li>
<li><a href="#20deferrecoverpaniclogrethrow">20 在defer/recover内再次panic的意义(log,rethrow)</a></li>
</ul>
</li>
</ul>
</li>
</ul>
</div>
</p>
<h2 id="320panicrecover">3-20 panic和recover</h2>
<p>相比error，panic、recover在使用方法上更接近try...catch结构化异常。</p>
<ul>
<li>内置函数，而非语句。</li>
<li>参数为接口类型，可以是任何对象。</li>
<li>无论是否执行recover，延迟调用都会执行。</li>
<li>仅最后一个panic会被捕获。</li>
<li>只能在延迟函数中直接使用recover。</li>
</ul>
<p>Go语言中，panic、recover和try...catch结构化异常非常相似。官方文档推荐不要使用panic尽量使用error。panic相当于抛出异常，在defer里面捕获异常。正常情况下，使用error方式来实现，当框架中做流程干涉可以考虑panic，例如数据库打开错误。</p>
<h3 id="20defer">20 确保defer得以执行</h3>
<pre><code class="go language-go">func main() {
    defer println("b")
    defer func() {
        println("a")
    }()
    panic("error")
}
</code></pre>
<h3 id="20panic">20 仅最后一个panic会被捕获</h3>
<pre><code class="go language-go">func main() {
    defer func() {
        fmt.Println(recover())
    }()
    defer func() {
        panic("b")
    }()
    panic("a")
}
</code></pre>
<h3 id="20recover">20 必须在延迟函数中直接调用recover</h3>
<p>panic相当于抛出异常，recover捕获异常。recover要通过上一级调用堆栈链来获得它的错误信息，panic把错误挂到栈上面的。</p>
<pre><code class="go language-go">func test() {
    fmt.Println(recover())
}
func main() {
    // defer func() { // success
    // fmt.Println(recover())
    // }()
    defer func() { test() }() // failure
    //defer fmt.Println(recover())
    //err := recover()
    //defer fmt.Println(err)

    // defer test() // success
    // defer recover() // failure
    panic("error") //raise
}
</code></pre>
<p>recover必须在延迟函数中直接调用。<code>defer recover()</code>捕获不到，<code>defer func() // success</code>可以捕获。</p>
<p>延迟函数必须是顶级的。<code>defer test()</code>可以捕获，<code>defer func() { test() }()</code>在第二级里面，捕获不到。</p>
<p>这样实现是因为在runtime层面要维持调用堆栈，如果深度非常深的情况下，并不能直接反应当前panic错误。所以panic的要求第一必须在延迟函数内部调用，第二必须是第一级延迟函数。</p>
<h3 id="20">20 使用匿名函数保护代码片段</h3>
<pre><code class="go language-go">func test(x, y int) {
    z := 0
    func() {
        defer func() {
            if recover() != nil {
                z = 0
            }
        }()
        z = x / y
    }()
    println("x / y =", z)
}
func main() {
    test(5, 0)
}
</code></pre>
<p>使用匿名函数保护不会被零除，这和结构化异常的方式差不多。不推荐这种写法，因为我们推荐检查错误条件是前置条件而不是后置条件。defer在函数结束的时候才执行，是一种清理手段，对于算法来说，前置检查条件是算法正常执行的基础和算法本身不能分割的。</p>
<h3 id="20errorvspanic">20 error vs panic</h3>
<ul>
<li>error表达一个“正常”返回结果。</li>
<li>panic表达不可恢复，导致系统无法正常工作的错误。</li>
<li>error不会中断执行流程。</li>
<li>panic中断执行流程，立即执行延迟调用。</li>
<li>除非必要，否则优先使用error模式。</li>
</ul>
<h3 id="20deferrecoverpaniclogrethrow">20 在defer/recover内再次panic的意义(log,rethrow)</h3>
<p>Go语言里经常会这样，使用recover抓到错误，记录日志然后继续抛出去，这段代码专门用来错误记录。另外一层抓到错误对错误进行处理。很显然它可以中止程序它不关心错误干什么。</p>
<p>为什么要分开呢，因为去掉一段对另一段没有影响，它们中间没有依赖关系，相当于可插拔中间件机制。</p>
<pre><code class="go language-go">func test() {
    //对错误进行处理
    defer func() {
        if err := recover(); err != nil {
            os.Exit(1)
        }
    }()
    //错误记录
    defer func() {
        err := recover() //try...except
        log(err)
        panic(err)
    }()
    panic("xxx") //raise
}
</code></pre></div></article>